/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    Greet: typeof import('./src/components/Greet.vue')['default']
    IconMdiAccount: typeof import('~icons/mdi/account')['default']
    IconRiAppleFill: typeof import('~icons/ri/apple-fill')['default']
    IconRiBarChartBoxLine: typeof import('~icons/ri/bar-chart-box-line')['default']
    IconRiChartBoxOutline: typeof import('~icons/ri/chart-box-outline')['default']
    IconRiDatabaseLine: typeof import('~icons/ri/database-line')['default']
    IconRiSettings3Line: typeof import('~icons/ri/settings3-line')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
  }
}
