//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod categories;
pub mod dependencies;
pub mod editors;
pub mod grand_total;
pub mod languages;
pub mod machines;
pub mod operating_systems;
pub mod projects;
pub mod range;
pub mod wakatime;
