//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::categories::Entity as Categories;
pub use super::dependencies::Entity as Dependencies;
pub use super::editors::Entity as Editors;
pub use super::grand_total::Entity as GrandTotal;
pub use super::languages::Entity as Languages;
pub use super::machines::Entity as Machines;
pub use super::operating_systems::Entity as OperatingSystems;
pub use super::projects::Entity as Projects;
pub use super::range::Entity as Range;
